language: node_js
env:
  - CXX="g++-4.8"
node_js:
  - "4"
  - "5"
  - "iojs"
  - "iojs-2"
  - "iojs-1"
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
